stages:
  - coverage
  - builddocs
  - deploy

test:
  tags:
    - linux
  stage: coverage
  image: cirrusci/flutter
  script:
    - sed -i s/#//g pubspec.yaml
    - rm -r example
    - flutter pub get
    - flutter test --enable-experiment=non-nullable
  
code_analyze:
  tags:
    - docker
  stage: coverage
  image: cirrusci/flutter
  dependencies: []
  script:
    - flutter format lib/ test/ test_driver/ --set-exit-if-changed
    - flutter analyze

build_api_doc:
  tags:
    - docker
  stage: builddocs
  image: cirrusci/flutter
  script:
    - dartdoc --exclude "dart:async,dart:collection,dart:convert,dart:core,dart:developer,dart:io,dart:isolate,dart:math,dart:typed_data,dart:ui"
  artifacts:
    paths:
      - doc/api/
  only:
    - main

pages:
  tags:
    - linux
  stage: deploy
  image: alpine:latest
  script:
    - mv doc/api/ public
  dependencies:
    - build_api_doc
  artifacts:
    paths:
      - public
  only:
    - main